language: python
python:
    - "2.7"
    - "3.3"
install:
    # Upgrade pip and setuptools to get ones with `wheel` support
    - pip install --upgrade pip setuptools
    - pip install -e .[docs]
script:
    - python setup.py nosetests
    - python setup.py build_sphinx
after_success:
    - coveralls
