language: python
cache:
    apt
python:
    - "2.7"
    - "3.3"
install:
    # Install postgress client library
    - sudo apt-get install libpq-dev
    # Upgrade pip and setuptools to get ones with `wheel` support
    - pip install --upgrade pip setuptools
    # Dependencies only for travis
    - pip install coveralls
    # Install the software itself
    - pip install -e .[docs]
    # Get test database instance and migrate it
    - source development_vars.sh
    - trafficdb_webapp db upgrade
script:
    - python setup.py nosetests
    - python setup.py build_sphinx
after_success:
    - coveralls
