language: python
cache:
    apt
python:
    - "2.7"
    - "3.3"
env:
    # USe postgression to get a test database
    - SQLALCHEMY_TEST_DATABASE_URI=$(curl -s http://api.postgression.com)
install:
    # Install postgress client library
    - sudo apt-get install libpq-dev
    # Upgrade pip and setuptools to get ones with `wheel` support
    - pip install --upgrade pip setuptools
    # Dependencies only for travis
    - pip install coveralls
    # Install the software itself
    - pip install -e .[docs]
    # Migrate development DB (note the requirement to set SQLALCHEMY_DATABASE_URI)
    - SQLALCHEMY_DATABASE_URI=$SQLALCHEMY_TEST_DATABASE_URI webapp db upgrade
script:
    - python setup.py nosetests
    - python setup.py build_sphinx
after_success:
    - coveralls
