"""Create uuid column and index on links.

Revision ID: 1a3b47c5a0
Revises: 38fc5079bd1
Create Date: 2014-09-26 12:18:17.144273

"""

# revision identifiers, used by Alembic.
revision = '1a3b47c5a0'
down_revision = '38fc5079bd1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from trafficdb.models import uuid_generate_v4

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION "uuid-ossp";') # For uuid_generate_v4
    op.add_column('links', sa.Column('uuid', postgresql.UUID(), server_default=uuid_generate_v4(), nullable=False))
    op.create_index('ix_link_uuid', 'links', ['uuid'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_link_uuid', table_name='links')
    op.drop_column('links', 'uuid')
    op.execute('DROP EXTENSION "uuid-ossp";')
    ### end Alembic commands ###
