"""link_aliases table and indexes

Revision ID: 375e15ea383
Revises: 4c2d727186
Create Date: 2014-09-30 10:38:19.146386

"""

# revision identifiers, used by Alembic.
revision = '375e15ea383'
down_revision = '4c2d727186'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('is_link_aliases_name', 'link_aliases', ['name'], unique=True)
    op.create_index('ix_link_aliases_link_id', 'link_aliases', ['link_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_link_aliases_link_id', table_name='link_aliases')
    op.drop_index('is_link_aliases_name', table_name='link_aliases')
    op.drop_table('link_aliases')
    ### end Alembic commands ###
