"""Geometry column for links

Revision ID: 38fc5079bd1
Revises: 585100e0455
Create Date: 2014-09-25 16:23:49.366019

"""

# revision identifiers, used by Alembic.
revision = '38fc5079bd1'
down_revision = '585100e0455'

from alembic import op
import sqlalchemy as sa
import geoalchemy2 as ga


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('geom',
        ga.Geometry(geometry_type='LINESTRING', srid=4326),
        server_default=sa.text("ST_GeomFromText('LINESTRING EMPTY', 4326)"), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'geom')
    ### end Alembic commands ###
