"""Add observation observed_at index

Revision ID: 390e44cdfbe
Revises: 1ab13f7b5ba
Create Date: 2014-09-25 14:43:42.698569

"""

# revision identifiers, used by Alembic.
revision = '390e44cdfbe'
down_revision = '1ab13f7b5ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_observation_observed_at', 'observations', ['observed_at'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_observation_observed_at', table_name='observations')
    ### end Alembic commands ###
