"""And observation time and link id two-column index.

Revision ID: 3a6fc832a45
Revises: 390e44cdfbe
Create Date: 2014-09-25 14:48:28.917128

"""

# revision identifiers, used by Alembic.
revision = '3a6fc832a45'
down_revision = '390e44cdfbe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_observation_observed_at_link_id', 'observations', ['observed_at', 'link_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_observation_observed_at_link_id', table_name='observations')
    ### end Alembic commands ###
