"""spatial index on links

Revision ID: 4c2d727186
Revises: 8fc9e3cc0a
Create Date: 2014-09-26 15:01:43.779140

"""

# revision identifiers, used by Alembic.
revision = '4c2d727186'
down_revision = '8fc9e3cc0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_link_geom', 'links', ['geom'], unique=False, postgresql_using='gist')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_link_geom', table_name='links')
    ### end Alembic commands ###
