"""Create PostGIS extension

Revision ID: 585100e0455
Revises: 3a6fc832a45
Create Date: 2014-09-25 15:46:45.174892

"""

# revision identifiers, used by Alembic.
revision = '585100e0455'
down_revision = '3a6fc832a45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION postgis;')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP EXTENSION postgis;')
    ### end Alembic commands ###
