"""Initial database migration

Revision ID: 7dc1a66bb8
Revises: None
Create Date: 2014-09-24 15:36:35.984051

"""

# revision identifiers, used by Alembic.
revision = '7dc1a66bb8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('type', sa.Enum('SPEED', 'FLOW', 'OCCUPANCY', name='observation_types'), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations')
    op.drop_table('links')
    ### end Alembic commands ###
